// 出題用の「問題プール」を複数用意しておく。
// 本来はJSON/TSVアップロードで登録する想定だが、
// まずはこの固定データでロビー〜出題の流れを作る。
// ホスト側の「ルームを作る」画面で、この中から使うプールと出題数を選べるようにする。

export type QuizPool = {
  id: string;
  title: string;
  authorName: string;
  description: string;
  isTutorial？: boolean; // trueの場合、ホスト側で出題数選択を1問固定にし、各画面に説明を表示する
  questions: {
    body: string;
    choices: string[];
    correctIndex: number;
    timeLimitSec: number;
    points: number;
  }[];
};

// チュートリアルモード用の1問だけのプール。
// ゲームの流れ(予告→出題→結果発表→終了)を実際に体験しながら理解してもらうためのもの。
export const tutorialPool: QuizPool = {
  id: 'tutorial',
  title: 'チュートリアル(ゲームの流れを説明)',
  authorName: '開発用',
  description: '1問だけの練習用。画面の流れを説明しながら進みます',
  isTutorial: true,
  questions: [
    {
      body: 'これはチュートリアル問題です。「クイズ」を選んでください',
      choices: ['クイズ', 'アンケート', '宿題', '面接'],
      correctIndex: 0,
      timeLimitSec: 20,
      points: 1000,
    },
  ],
};
 

export const quizPools: QuizPool[] = [
  {
    id: 'general-20',
    title: '一般常識クイズ(20問プール)',
    authorName: '開発用',
    description: '雑学・一般常識を中心にした20問のプール',
    questions: [
      {
        body: '1853年生まれのポスト印象派の画家で、『アルルの跳ね橋』や『ひまわり』などで知られる人物は誰でしょう？',
        choices: ['モネ', 'セザンヌ', 'ゴーギャン', 'ゴッホ'],
        correctIndex: 3,
        timeLimitSec: 20,
        points: 1000,
      },
      {
        body: '記号「dB」で表される、主に騒音のレベルを示す際などに用いられる単位は何でしょう？',
        choices: ['デシベル', 'キロメートル', 'メートル', 'キログラム'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 1000,
      },
      {
        body: 'わずかな元手で大きな利益を得ることを俗に「海老で何を釣る」というでしょう？',
        choices: ['さめ', 'たい', 'しらす', 'まぐろ'],
        correctIndex: 1,
        timeLimitSec: 10,
        points: 500,
      },
      {
        body: '前身となった組織・社団法人東京放送局の事業を継承する形で、1950年に放送法に基づき設立された、日本の公共放送機関である「日本放送協会」のことを、アルファベット3文字の略称で何というでしょう？',
        choices: ['NHK', 'BCC', 'CBC', 'ABC'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '元々は麦わらを利用していたことからその名前が付けられた、容器に入った飲料を飲む際に使われる細い管状の道具は何でしょう？',
        choices: ['コップ', 'ストロー', 'グラス', 'マドラー'],
        correctIndex: 1,
        timeLimitSec: 10,
        points: 500,
      },
      {
        body: '東京都千代田区永田町1丁目にある、かつての名称を「帝国議会議事堂」といった建物は何でしょう？',
        choices: ['国会議事堂', '東京駅', '日本銀行本店', '新宿迎賓館赤坂離宮'],
        correctIndex: 0,
        timeLimitSec: 20,
        points: 1000,
      },
      {
        body: '「メディア良化法」が制定された架空の日本で、図書館の役割と本の自由を守るために戦う図書隊の姿が描かれた、有川ひろの連作小説は何シリーズでしょう？',
        choices: ['図書館難民', '図書館抗争', '図書館戦隊', '図書館戦争'],
        correctIndex: 3,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '北米大陸にあるスペリオル湖、ミシガン湖、ヒューロン湖、エリー湖、オンタリオ湖の5つの湖を総称して一般に何と呼ぶでしょう？',
        choices: ['五連湖', '五湖', '五大湖', '五小湖'],
        correctIndex: 2,
        timeLimitSec: 20,
        points: 1000,
      },
      {
        body: '自らが大切に世話をしたり育てたりすることを、ある調味料の名前を使って「何に掛ける」というでしょう？',
        choices: ['手塩', '天塩', 'みりん', '天つゆ'],
        correctIndex: 0,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: '葛飾北斎の『富嶽三十六景』において、あとから追加された10枚のことを、初めに摺られた「表富士」に対して何というでしょう？',
        choices: ['鏡富士', '裏富士', '二番富士', '続富士'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: 'その名はギリシャ語で「新しい」を意味する言葉に由来し、看板などに使われる放電管の封入ガスとして用いられる、原子番号10、元素記号Neの元素は何でしょう？',
        choices: ['ネオン', 'アルゴン', 'キセノン', 'アセチレン'],
        correctIndex: 0,
        timeLimitSec: 20,
        points: 1200,
      },
      {
        body: 'ゲームジャンルの1つ「RPG」とは、何という言葉の略でしょう？',
        choices: ['Role-Playing Game', 'Real Playing Game', 'Rapid Play Game', 'Remote Play Game'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '東京ディズニーリゾートに来園する人々のことを、従業員を指す「キャスト」に対する表現で何というでしょう？',
        choices: ['ゲスト', 'ファン', '訪問者', '利用者'],
        correctIndex: 0,
        timeLimitSec: 10,
        points: 300,
      },
      {
        body: '一般に、「ピンキーリング」はどの指にはめる指輪でしょう？',
        choices: ['親指', '人差し指', '小指', '薬指'],
        correctIndex: 2,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '1つの物事に関連して多くの物事が次から次へと明らかになる様子を、ある植物にたとえて「何式」というでしょう？',
        choices: ['かずら式', '芋づる式', '桜式', '竹式'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '日本の数の単位で「兆」の1万倍を表す単位は何でしょう？',
        choices: ['兆', '京', '億', '垓'],
        correctIndex: 1,
        timeLimitSec: 10,
        points: 300,
      },
      {
        body: '太陽系で一番大きい惑星は？',
        choices: ['地球', '土星', '木星', '海王星'],
        correctIndex: 2,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '「情けは人の為ならず」の意味として正しいのは？',
        choices: [
        '情けをかけると相手のためにならない',
        '情けをかけると巡り巡って自分にも良いことがある',
        '情けをかけるべきではない',
        '人に情けは不要だ',
        ],
        correctIndex: 1,
        timeLimitSec: 25,
        points: 1200,
      },
    ],
  },
  {
    id: 'science-tech-12',
    title: '理科・IT雑学クイズ(12問プール)',
    authorName: '開発用',
    description: '理科やIT・数学寄りの雑学を集めた12問のプール',
    questions: [
      {
        body: '「立派な」を意味する英単語respectableの否定形は何。',
        choices: ['irrespectable', 'disrespectable', 'unrespectable', 'inrespectable'],
        correctIndex: 2,
        timeLimitSec: 10,
        points: 900,
      },
      {
        body: '硫酸銅水溶液は何色を示すか。',
        choices: ['青色', '緑色', '橙色', '紫色'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 600,
      },
      {
        body: 'もともとスペインで「クジラを殺すもの」と呼ばれていた生物は何。',
        choices: ['シャチ', 'サメ', 'ピラニア', 'そんなものはない'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 1000,
      },
      {
        body: '中東の国「オマーン」の首都は何。',
        choices: ['マスカット', 'アップル', 'ライチ', 'パイナポー'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 1200,
      },
      {
        body: '日本で初めてノーベル物理学賞を受賞した人物は誰。',
        choices: ['江崎玲於奈', '赤崎勇', '中村修二', '湯川秀樹'],
        correctIndex: 3,
        timeLimitSec: 15,
        points: 700,
      },
      {
        body: '急がば回れの語源となった場所はどこ？',
        choices: ['富士山', '清水寺', '厳島神社', '琵琶湖'],
        correctIndex: 3,
        timeLimitSec: 15,
        points: 500,
      },
      {
        body: 'タラバガニは生物学上、カニではなく何の仲間？',
        choices: ['くも', 'ヤドカリ', 'エビ', 'ザリガニ'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: 'キリマンジャロはどこで区切るのが正しいでしょうか',
        choices: ['キリマ・ンジャロ', 'キリマン・ジャロ', 'キリ・マンジャロ', 'キ・リマンジャロ'],
        correctIndex: 0,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: 'アナゴさんの出身大学は？',
        choices: ['京都大学', '東京大学', '早稲田大学', '一橋大学'],
        correctIndex: 0, 
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: 'オリンピックシンボルの五輪マーク、一番左のマークは何色でしょう？',
        choices: ['黒', '緑', '青', '黄'],
        correctIndex: 2,
        timeLimitSec: 10,
        points: 500,
      },
      {
        body: 'ソーラン節は何の漁を表した歌でしょう？',
        choices: ['イワシ', 'ニシン', 'サケ', 'マグロ'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: 'ダンゴムシの呼吸法は？',
        choices: ['皮膚呼吸', '肺呼吸', 'エラ呼吸', '呼吸しない'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '日本の大統領で殺されてしまった人数は？',
        choices: ['0', '4', '7', '9'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 1000,
      },
      {
        body: 'アホウドリの名前の由来はなんでしょう？',
        choices: ['アホーと鳴くから', '人間にすぐ捕まるから', 'あほみたいな顔をしているから', '阿波踊りみたいに踊っているように飛ぶから'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 500,
      },
      {
        body: '日本で最初に発売されたアイスクリームの値段は？',
        choices: ['８００円', '３０００円', '６０００円', '８０００円'],
        correctIndex: 3,
        timeLimitSec: 15,
        points: 1200,
      },
      {
        body: 'マウスを動かした距離を表す単位は？',
        choices: ['ミッキー', 'センチメートル', 'インチ', 'ミニー'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: 'インスタントラーメンを開発したのはだれか？',
        choices: ['安藤百福', 'エジソン', '石破茂', '山口一郎'],
        correctIndex: 0,
        timeLimitSec: 10,
        points: 500,
      },
      {
        body: '海で一番早く泳ぐ生き物はどれ？',
        choices: ['さめ', 'カツオ', 'メカジキ', 'クジラ'],
        correctIndex: 2,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: 'オリンピック能力5つの輪は何を表している？',
        choices: ['平和', '大陸', '仲間', 'お金'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '月の上で行われたことがあるスポーツは？',
        choices: ['ゴルフ', 'ポーカー', 'テニス', 'サッカー'],
        correctIndex: 0,
        timeLimitSec: 20,
        points: 1000,
      },
      {
        body: '宇宙服は一着何円？',
        choices: [
          '１０００万円',
          '１億円',
          '１０億円',
          '１００億円',
        ],
        correctIndex: 2,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: 'イーロン・マスクの長男の名前は？',
        choices: ['Twitter :# WX YZ', 'シーソン・マスク', 'X Æ A-Xii', 'マスク・マスク'],
        correctIndex: 2,
        timeLimitSec: 20,
        points: 900,
      },
      {
        body: '存在しない魚料理は？',
        choices: ['サマック・マシュウィ', 'あんこうの泥沼鍋', '深海魚のすき焼き', 'うつぼのたたき'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 1000,
      },
      {
        body: '東京ディズニーランドのシンデレラ城の高さは地上から何メートル？',
        choices: ['約31M', '約41M', '約51M', '約61M'],
        correctIndex: 2,
        timeLimitSec: 15,
        points: 500,
      },
      {
        body: '万里の長城の長さは？',
        choices: ['約1万4105㎞', '約1万7931㎞', '約9408㎞', '約2万1196㎞'],
        correctIndex: 3,
        timeLimitSec: 20,
        points: 1000,
      },
      {
        body: 'マンボウの子供は生まれてから大人になるまでに何％が死んでしまうか？',
        choices: ['約75%', '約87.98%', '約99.99%', '約37.65% '],
        correctIndex: 2,
        timeLimitSec: 15,
        points: 500,
      },
      {
        body: '日本が一番最初にオリンピックで金メダルを取った競技は？',
        choices: ['柔道', '陸上', '水泳', '体操'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 1000,
      },
      {
        body: 'やばいの語源は何時代から？',
        choices: ['平成', '大正', '平安', '江戸'],
        correctIndex: 3,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '音痴は神経心理学の分野では何の略語として用いられる？',
        choices: ['失音楽', '音楽音痴', '声帯ピッチアウト現象', '鼓膜声帯同期エラー'],
        correctIndex: 0,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: 'ジンバブエの2008年の年間インフレ率は？',
        choices: ['約897垓%','約796億%','約375京%','約153不可説不可説転'],
        correctIndex: 0,
        timeLimitSec: 25,
        points: 1000,
      },
      {
        body: 'ボストン茶会事件で投げられた茶箱の数は？',
        choices: ['572箱', '342箱', '264箱', '857箱'],
        correctIndex: 1,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: '世界で一番暑い日を記録したのはどこ？',
        choices: ['アメリカ', 'インド', 'オーストラリア', 'エジプト'],
        correctIndex: 0,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: '地球を歩いて一周するには何日かかる？',
        choices: ['3日', '33日', '333日', '3333日'],
        correctIndex: 2,
        timeLimitSec: 20,
        points: 1000,
      },
      {
        body: 'グリンピースは誰の子供？',
        choices: ['えだまめ', '大豆', 'えんどう豆', 'そら豆'],
        correctIndex: 2,
        timeLimitSec: 10,
        points: 300,
      },
      {
        body: 'サッカーワールドカップ初回大会の優勝国は？',
        choices: ['フランス', 'アルゼンチン', 'ウルグアイ', 'ブラジル'],
        correctIndex: 2,
        timeLimitSec: 20,
        points: 1000,
      },
      {
        body: 'イチローの日米通算安打数は？',
        choices: [
          '4000本',
          '3085本',
          '4367本',
          '2945本',
        ],
        correctIndex: 2,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: 'サカナクションのボーカル担当の人物名は？',
        choices: ['山下達郎', '玉置浩二', '山口一郎', '尾崎豊'],
        correctIndex: 2,
        timeLimitSec: 20,
        points: 700,
      },
      {
        body: '魚が小魚を捕食する現象やその水面の動きのことを何という？',
        choices: ['ベイト', 'ボイル', 'ホイル', 'カット'],
        correctIndex: 1,
        timeLimitSec: 25,
        points: 1000,
      },
      {
        body: '存在しないフレンチはどれ？',
        choices: ['ポワレ', 'エスカロップ', 'パルファン・ド・フォレ', 'アレニェ・ドゥ・ポー'],
        correctIndex: 2,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: 'ポケモンのマグカルゴの体温は？',
        choices: ['500℃', '700℃', '1000℃', '10000℃'],
        correctIndex: 3,
        timeLimitSec: 15,
        points: 800,
      },
      {
        body: '最新のみそきんの味の種類は？',
        choices: ['カレー', 'しょうゆ', 'とんこつ', 'カルボナーラ'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 700,
      },
      {
        body: '宮崎先生の下の名前は？',
        choices: ['祐樹', '勇気', '勇樹', '祐気'],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 500,
      },
      {
        body: '古長先生の下の名前は？',
        choices: ['麻矢', '真矢', '麻耶', '真耶'],
        correctIndex: 3,
        timeLimitSec: 15,
        points: 600,
      },
      {
        body: 'haveの意味でないものはどれ？',
        choices: ['（恨みなどを）抱く', '示す', '壊す', 'してもらう'],
        correctIndex: 2,
        timeLimitSec: 15,
        points: 1000,
      },
      {
        body: 'farmer Aは野菜を売る。Farmer Bは卵を売る。では、farmer Cは何を売る？',
        choices: [
          'ハム',
          'シリアル',
          '薬',
          'タバコ',
        ],
        correctIndex: 2,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: '今年のMAJに出演していなかったアーティストは？',
        choices: ['YOASOBI', 'M!LK', '米津玄師', 'HANA'],
        correctIndex: 1,
        timeLimitSec: 15,
        points: 700,
      },
      {
        body: '蝶が足で感じることが出来るのは何？',
        choices: ['味', '音楽', '重力の重さ', '匂い'],
        correctIndex: 0,
        timeLimitSec: 25,
        points: 1200,
      },
      {
        body: 'この中で素数の定義に沿った数字はどれ？',
        choices: ['1', '57', '91', 'この中にはない'],
        correctIndex: 3,
        timeLimitSec: 15,
        points: 300,
      },
      {
        body: 'この中で医学部がない大学はどれ？',
        choices: ['弘前大学', '東北大学', '福島大学', '山形大学'],
        correctIndex: 2,
        timeLimitSec: 15,
        points: 900,
      },
      {
        body: '質量Mの物体が水平右方向に6メートル移動するとき、垂直抗力がこの物体にした仕事は？',
        choices: ['6M', '36M^2', '0', '36'],
        correctIndex: 2,
        timeLimitSec: 10,
        points: 500,
      },
      {
        body: '日本国憲法が公布されたのはいつ？',
        choices: [ '1946年11月3日', '1946年5月3日','1947年11月3日', '1947年5月3日' ],
        correctIndex: 0,
        timeLimitSec: 15,
        points: 300,
      },
      {
        body: '答えは簡単です。2^13は？',
        choices: ['簡単', '1024', '2048', '8192'],
        correctIndex: 3,
        timeLimitSec: 10,
        points: 1200,
      },
    ],
  },
];
