// 動作確認用のサンプルクイズ。
// 本来はJSON/TSVアップロードで登録する想定だが、
// まずはこの固定データでロビー〜出題の流れを作る。
// 20問用意しておき、実際のルーム作成時にはこの中からランダムに10問を選んで出題する。
export const sampleQuiz = {
  title: 'サンプルクイズ',
  authorName: '開発用',
  description: '動作確認用の20問プールから10問出題',
  shuffle: true,
  questionLimit: 10,
  questions: [
    {
      body: '日本の首都は?',
      choices: ['大阪', '東京', '京都', '名古屋'],
      correctIndex: 1,
      timeLimitSec: 20,
      points: 1000,
    },
    {
      body: '1 + 1 は?',
      choices: ['1', '2', '3', '4'],
      correctIndex: 1,
      timeLimitSec: 10,
      points: 500,
    },
    {
      body: '富士山がある都道府県の組み合わせは?',
      choices: ['山梨県と静岡県', '長野県と山梨県', '静岡県と愛知県', '山梨県のみ'],
      correctIndex: 0,
      timeLimitSec: 20,
      points: 1000,
    },
    {
      body: '日本で一番人口が多い都道府県は?',
      choices: ['大阪府', '神奈川県', '東京都', '愛知県'],
      correctIndex: 2,
      timeLimitSec: 15,
      points: 1000,
    },
    {
      body: '1年は何日?(うるう年を除く)',
      choices: ['364日', '365日', '366日', '360日'],
      correctIndex: 1,
      timeLimitSec: 10,
      points: 500,
    },
    {
      body: '水の化学式は?',
      choices: ['CO2', 'O2', 'H2O', 'NaCl'],
      correctIndex: 2,
      timeLimitSec: 15,
      points: 800,
    },
    {
      body: '日本で一番高い山は?',
      choices: ['槍ヶ岳', '富士山', '北岳', '御嶽山'],
      correctIndex: 1,
      timeLimitSec: 10,
      points: 500,
    },
    {
      body: '世界で一番広い大陸は?',
      choices: ['アフリカ大陸', 'ユーラシア大陸', '北アメリカ大陸', '南極大陸'],
      correctIndex: 1,
      timeLimitSec: 20,
      points: 1000,
    },
    {
      body: '虹の色は一般的に何色とされる?',
      choices: ['5色', '6色', '7色', '8色'],
      correctIndex: 2,
      timeLimitSec: 15,
      points: 800,
    },
    {
      body: '人間の心臓の部屋(心房・心室)はいくつ?',
      choices: ['2つ', '3つ', '4つ', '5つ'],
      correctIndex: 2,
      timeLimitSec: 20,
      points: 1000,
    },
    {
      body: '10進数の「10」を2進数にすると?',
      choices: ['1000', '1010', '1100', '1001'],
      correctIndex: 1,
      timeLimitSec: 25,
      points: 1200,
    },
    {
      body: '日本の国花とされる花は?(複数正解ありのうち代表的なもの)',
      choices: ['チューリップ', '桜', 'ひまわり', 'コスモス'],
      correctIndex: 1,
      timeLimitSec: 15,
      points: 800,
    },
    {
      body: '光の速さに一番近いのは?',
      choices: ['秒速約30万km', '秒速約30万m', '秒速約3万km', '秒速約300km'],
      correctIndex: 0,
      timeLimitSec: 20,
      points: 1200,
    },
    {
      body: '将棋で最初に動かせる「歩」の数は?',
      choices: ['8枚', '9枚', '10枚', '7枚'],
      correctIndex: 0,
      timeLimitSec: 15,
      points: 800,
    },
    {
      body: '1週間は何日?',
      choices: ['5日', '6日', '7日', '8日'],
      correctIndex: 2,
      timeLimitSec: 10,
      points: 300,
    },
    {
      body: '日本で最も面積が広い都道府県は?',
      choices: ['北海道', '岩手県', '福島県', '長野県'],
      correctIndex: 0,
      timeLimitSec: 15,
      points: 800,
    },
    {
      body: '三角形の内角の和は?',
      choices: ['90度', '180度', '270度', '360度'],
      correctIndex: 1,
      timeLimitSec: 15,
      points: 800,
    },
    {
      body: '日本の通貨単位は?',
      choices: ['ウォン', '元', '円', 'ドル'],
      correctIndex: 2,
      timeLimitSec: 10,
      points: 300,
    },
    {
      body: '太陽系で一番大きい惑星は?',
      choices: ['地球', '土星', '木星', '海王星'],
      correctIndex: 2,
      timeLimitSec: 15,
      points: 800,
    },
    {
      body: '「情けは人の為ならず」の意味として正しいのは?',
      choices: [
        '情けをかけると相手のためにならない',
        '情けをかけると巡り巡って自分にも良いことがある',
        '情けをかけるべきではない',
        '人に情けは不要だ',
      ],
      correctIndex: 1,
      timeLimitSec: 25,
      points: 1200,
    },
  ],
};
